---
title: "Identificación de patrones lingüísticos Emberá en la taxonomía de plantas de la Serranía de Abibe"
author:
  - name: "Juanita Upegui-Castro"
    email: juanita.upegui@udea.edu.co
    affiliation: 
      - id: udea
        name: "Grupo de Estudios Botánicos GEOBOTA, Instituto de Biología, Facultad de Ciencias Exactas y Naturales, Universidad de Antioquia UdeA"
    # orcid: 0000-0000-0000-0000
    # url: /people/apellido-apellido_nombre/index.qmd
  - name: "Simón Silva-Arroyave"
    email: simon.silva@udea.edu.co
    affiliation:
      - ref: udea
    # orcid: 0000-0000-0000-0000
    # url: /people/apellido-apellido_nombre/index.qmd
  - name: "Fernando Alveiro Alzate-Guarin"
    email: alveiro.alzate@udea.edu.co
    affiliation:
      - ref: udea
    orcid: 0000-0002-4916-8897
    # url: /people/alzate-guarin_fernando-alveiro/index.qmd
date: "2024-11-06 14:00"

categories:
  - Emberá
  - Etnobotánica
  - Etnotaxonomía
  - Sitios sagrados

# draft: true
---

## Resumen

En la cordillera Occidental, al noroccidente del departamento de Antioquia, Colombia, se encuentra la Serranía de Abibe, donde están establecidas las comunidades Emberá de Polines, Chigorodocito y Guapá, dentro de los resguardos indígenas de Polines y Yhaberaradó. Este trabajo busca identificar la existencia de patrones lingüísticos de la lengua Emberá, utilizados para nombrar las plantas de tres sitios sagrados para esta comunidad, ubicados en una zona de vida correspondiente a bosque muy húmedo tropical (bmh-T). Un equipo interdisciplinar realizó exploraciones entre finales de 2019 y principios de 2020 en los asentamientos Emberá de Polines, Chigorodocito y Guapá Alto, de las cuales se obtuvo una muestra limitada de flora de los tres sitios sagrados, todo bajo autorización y supervisión del Jaibaná. Los nombres en la lengua Emberá fueron proporcionados por el Jaibaná y miembros de la comunidad. La identificación de las especies recolectadas fue realizada en el herbario de la Universidad de Antioquia (HUA). Habiendo identificado 46 especies de plantas con sus nombres en lengua Emberá distribuidas en 36 géneros y 28 familias, se pudieron distinguir 16 prefijos y sufijos usados de manera consistente en estos, además de documentar con información de primera mano los usos etnobotánicos de estas especies dentro de la comunidad. Se lograron establecer categorías que agrupan dichos prefijos y sufijos en relación a la forma, hábito, uso y otras características como la fructificación. Se concluye que aunque la comunidad Emberá no tiene una nomenclatura biológica sistemática, es evidente la existencia de prefijos y sufijos usados para nombrar las plantas según las características de estas.

<!-- ## Póster -->

<!-- PDF -->
<!-- ```{=html} -->
<!-- <object data="presentacion_xii-ccb.pdf" type="application/pdf" width="800" height="540"> -->
<!--     <p>Parece que no tienes un plugin PDF para este navegador. -->
<!--     No pasa nada… puede hacer <a href="presentacion_xii-ccb.pdf">clic aquí  -->
<!--     para descargar el archivo PDF.</a></p> -->
<!-- </object> -->
<!-- ``` -->

<!-- ## Citación -->
