---
title: "Influencia del cambio climático sobre las concentraciones de polen aerovagante en la ciudad de Medellín, Colombia"
author:
  - name: "Yisela Melid Batista-Florez"
    email: melid.batista@udea.edu.co
    affiliation:
      - id: udea
        name: "Grupo de Estudios Botánicos GEOBOTA, Instituto de Biología, Facultad de Ciencias Exactas y Naturales, Universidad de Antioquia UdeA"
    # url: /people/batista-florez_yisela-melid/index.qmd
  - name: "Álex Espinosa-Correa"
    email: alex.espinosa@udea.edu.co
    affiliation:
      - ref: udea
    orcid: 0000-0002-7353-1182
    # url: /people/espinosa-correa_alex/index.qmd
  - name: "Fernando Alveiro Alzate-Guarin"
    email: alveiro.alzate@udea.edu.co
    affiliation:
      - ref: udea
    orcid: 0000-0002-4916-8897
    # url: /people/alzate-guarin_fernando-alveiro/index.qmd
date: "2024-11-07 08:45"

categories:
  - Aerobiología
  - Contaminación atmosférica
  - ENSO
  - Palinología
  - Polinosis

# draft: true
---

## Resumen

Entre los elementos suspendidos de forma pasiva en la atmósfera y que son fuente de contaminación es posible identificar partículas de origen biótico o abiótico. Dentro de las partículas bióticas se exhibe una amplia gama de elementos que incluye granos de polen, esporas de hongos, bacterias, etc., sin embargo, hay un notable interés en el estudio del polen por los impactos en la salud humana, dado su potencial alergénico, en este sentido, es preciso realizar estudios durante períodos prolongados al permitir obtener mediciones más confiables y entender cómo fluctúan las concentraciones polínicas en función de variables climáticas. En los periodos de 2010-2011 y 2019-2022 se realizaron muestreos aerobiológicos en la ciudad de Medellín usando un muestreador tipo Hirst, donde se analizaron los datos comparativamente y se correlacionaron con las variables meteorológicas (humedad relativa, precipitación, temperatura y velocidad del viento). Se encontró un aumento significativo de la Integral Anual de Polen (APIn) entre los dos periodos evaluados, siendo para el primer muestreo 7371 polen\*día/m3 y para el segundo muestreo 40620, 45042 y 37723 polen\*día/m3 en cada año. En el primer muestreo los morfotipos más abundantes fueron *Fraxinus*, Poaceae y *Cecropia*, mientras que para el muestreo de 2019-2022 fueron *Cecropia*, Urticaceae y *Fraxinus*, lo cual evidencia un cambio en la abundancia de los morfotipos dominantes. La temperatura y la velocidad del viento tuvieron una correlación positiva con las concentraciones polínicas, mientras que las precipitaciones y la velocidad del viento presentaron correlaciones negativas. Los hallazgos evidencian un aumento de las concentraciones de polen aerovagante y sugieren que se puede asociar a los aumentos de temperatura en un contexto de cambio climático antropogénico.

<!-- ## Presentación -->

<!-- ```{=html} -->
<!-- <iframe class="slide-deck" src="presentacion_xii-ccb.html" title="Presentación XII CCB"></iframe> -->
<!-- ``` -->

<!-- Si no puedes ver la presentación, mírala haciendo [clic aquí](presentacion_xii-ccb.html). -->

<!-- ## Citación -->
